\i /db/migrations/001_init.sql
\i /db/migrations/002_master_data.sql
\i /db/migrations/003_auth_security.sql
\i /db/migrations/004_audit_log.sql
\i /db/migrations/005_anomaly_alerts.sql
\i /db/migrations/006_risk_scoring.sql
\i /db/migrations/007_master_data_constraints.sql
\i /db/migrations/008_playback_records.sql
\i /db/migrations/009_realtime_notifications.sql
\i /db/migrations/010_telemetry_map_matching.sql
\i /db/migrations/011_public_reports.sql
\i /db/migrations/012_passenger_tracking.sql
\i /db/migrations/013_public_report_reviews.sql
\i /db/migrations/014_phase15_network_sanctions.sql
\i /db/migrations/015_heatmap_data.sql
\i /db/migrations/016_mobile_public_release.sql
\i /db/migrations/017_wrong_direction_risk_backfill.sql
\i /db/migrations/018_current_state_tables.sql
\i /db/migrations/019_timescale_policies.sql
\i /db/migrations/020_public_report_evidence_processing.sql
\i /db/migrations/021_vehicle_device_health.sql
\i /db/migrations/022_phase19_emergency_response.sql
\i /db/seeds/001_seed.sql
\i /db/seeds/002_seed.sql
\i /db/seeds/003_osrm_snap_to_road.sql
\i /db/seeds/004_restore_geofences.sql
\i /db/seeds/005_demo_fleet_45.sql
